name: Analyze

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.3.5"
          cache: true
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Analyze
        uses: zgosalvez/github-actions-analyze-dart@v2
